[[constraint]]
  name = "github.com/pathfinder-cm/pathfinder-go-client"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[prune]
  go-tests = true
unused-packages = true
[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"
